seismology/web/main/routes/login.py
import json
import requests

from flask import (
    Blueprint,
    current_app,
    flash,
    make_response,
    redirect,
    url_for,
    render_template,
)
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_user, logout_user

from main.forms.login_forms import LoginForm
from .auth import User
from . import main

login_bp = Blueprint("login", __name__, url_prefix="/")


@login_bp.route("/login", methods=["POST", "GET"])
@register_breadcrumb(login_bp, ".", "Login")
def login():
    url = current_app.config["API_URL"] + "/auth/login"
    loginForm = LoginForm()

    if loginForm.validate_on_submit():
        # Enviar requests
        data = (
            '{"email":"'
            + loginForm.email.data
            + '", "password":"'
            + loginForm.password.data
            + '"}'
        )
        r = requests.post(
            current_app.config["API_URL"] + "/auth/login",
            headers={"content-type": "application/json"},
            data=data,
        )
        # Si la request se realiza con exito
        if r.status_code == 200:
            # Cargar valores del usuario de la respuesta
            user_data = json.loads(r.text)
            user = User(
                id=user_data.get("id"),
                email=user_data.get("email"),
                admin=user_data.get("admin"),
            )
            # Loguear objeto usuario
            login_user(user)
            # Crear una request de redireccion
            req = make_response(redirect(url_for("main.index")))
            # Setear cookie con el valor del token
            req.set_cookie("access_token", user_data.get("access_token"), httponly=True)
            # Realizar la request
            return req

        else:
            # Mostrar error de autenticacion
            flash("Incorrect user or password", "danger")
            return redirect(url_for("main.index"))
    return render_template("login.html", loginForm=loginForm)


# esta decorador no me lo reconoce
@login_bp.route("/logout")
def logout():
    # Crear una request de redireccion
    req = make_response(redirect(url_for("main.index")))
    # Vaciar cookie
    req.set_cookie("access_token", "", httponly=True)
    # Desloguear usuario
    logout_user()
    # Realizar request
    return req

seismology/web/main/routes/main.py
import json

from flask import Blueprint, current_app, flash, make_response, redirect, url_for
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_user, logout_user
import requests

from . import verified_seism

# from ..forms.login_form import LoginForm
from .auth import User

main = Blueprint("main", __name__, url_prefix="/")


@main.route("/")
@register_breadcrumb(main, "breadcrumbs", "Home")
def index():
    return redirect(url_for("verified_seism.index"))

seismology/web/main/routes/sensors.py
from flask import (
    Blueprint,
    render_template,
    current_app,
    redirect,
    url_for,
    flash,
    request,
)
from werkzeug.utils import header_property
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from ..utilities.functions import sendRequest
import requests, json
from flask_login import login_required
from .auth import admin_required
from ..forms.sensor_forms import SensorEditForm, SensorFilterForm

sensors = Blueprint("sensors", __name__, url_prefix="/sensors")


@sensors.route("/")
@login_required
@admin_required
@register_breadcrumb(sensors, ".", "Sensors")
def index():
    # Me carga los parametros de la url en el formulario
    # Con csrf = false elimino la proteccion para el formulario del filtrado
    filter = SensorFilterForm(request.args, meta={"csrf": False})
    # el data de r pasa un coso sin filtrado :V
    r = sendRequest(method="get", url="/users-info")

    filter.userId.choices = [
        (int(user["id"]), user["email"]) for user in json.loads(r.text)["Users"]
    ]

    filter.userId.choices.insert(0, [0, "All"])
    data = {}
    # Aplica los filtros y valido el formularios

    if filter.validate():
        if filter.userId.data != None and filter.userId.data != 0:
            data["userId"] = filter.userId.data
        if filter.name.data != None:
            data["name"] = filter.name.data
        if filter.status.data:
            data["status"] = filter.status.data
        if filter.active.data:
            data["active"] = filter.active.data
    # Realiza el ordenamiento

    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    # LA numeracion de la pagina(saber el numero)
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    # obtengo los datos de la api, pero tengo que consultar porque
    # no estoy comprendiendo mucho la logica del dato data=json.dumps
    r = sendRequest(method="get", url="/sensors", data=json.dumps(data), auth=True)

    if r.status_code == 200:
        sensors = json.loads(r.text)["Sensors"]
        pagination = {}
        # cargo en el diccionario de la paginacion el total de las paginas
        # pagina por pagina
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]
        title = "Sensors"
        return render_template(
            "sensors.html",
            title=title,
            sensors=sensors,
            filter=filter,
            pagination=pagination,
        )
    else:
        flash("Error de filtros", "danger")
        return redirect(url_for("sensors.index"))


@sensors.route("/view/<int:id>")
@login_required
@admin_required
@register_breadcrumb(sensors, ".view", "Sensor")
def view(id):
    r = sendRequest(method="get", url="/sensor/" + str(id), auth=True)
    if r.status_code == 404:
        flash("Sensor not found/sensor no econtrado", "danger")
        return redirect(url_for("sensors.index"))
    sensor = json.loads(r.text)
    title = "Sensor View"
    return render_template(
        "sensorview.html",
        title=title,
        sensor=sensor,
    )


@sensors.route("/delete/<int:id>")
@login_required
@admin_required
def delete(id):
    r = sendRequest(method="delete", url="/sensor/" + str(id), auth=True)
    flash("Sensor was delete", "danger")
    return redirect(url_for("sensors.index"))


@sensors.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
@admin_required
@register_breadcrumb(sensors, ".edit", "Edit Sensor")
def edit(id):
    form = SensorEditForm()
    r = sendRequest(method="get", url="/users-info")
    users = [(item["id"], item["email"]) for item in json.loads(r.text)["Users"]]
    form.userId.choices = users
    form.userId.choices.insert(0, [0, "Select one user"])
    if not form.is_submitted():
        r = sendRequest(method="get", url="/sensor/" + str(id), auth=True)
        if r.status_code == 404:
            flash("Sensor not found", "danger")
            return redirect(url_for("sensors.index"))
        sensor = json.loads(r.text)

        # carga los datos
        form.name.data = sensor["name"]
        form.port.data = sensor["port"]
        form.ip.data = sensor["ip"]
        form.status.data = sensor["status"]
        form.active.data = sensor["active"]

        #
        # Load users
        try:
            for user_id, user_email in users:
                if sensor["user"]["id"] == user_id:
                    form.userId.data = user_id

        except KeyError:
            pass

    if form.validate_on_submit():
        sensor = {
            "name": form.name.data,
            "ip": form.ip.data,
            "port": form.port.data,
            "status": form.status.data,
            "active": form.active.data,
            "userId": form.userId.data,
        }
        data = json.dumps(sensor)
        r = sendRequest(method="put", url="/sensor/" + str(id), data=data, auth=True)
        flash("Sensor edited", "success")
        return redirect(url_for("sensors.index"))

    return render_template("sensorEdit.html", id=id, form=form)

seismology/web/main/routes/unverified_seism.py
from flask import (
    Blueprint,
    render_template,
    current_app,
    redirect,
    url_for,
    flash,
    request,
)
from flask import blueprints
from requests.api import get
from werkzeug.utils import header_property
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from ..utilities.functions import sendRequest
import requests, json
from flask_login import login_required
from ..forms.unverified_seism_form import UnverifiedSeismEdit, UnverifiedSeismFilter

unverified_seism = Blueprint(
    "unverified_seism", __name__, url_prefix="/unverified-seism"
)


@unverified_seism.route("/")
@login_required
@register_breadcrumb(unverified_seism, ".", "Unverified Seism")
def index():
    filter = UnverifiedSeismFilter(request.args, meta={"csrf": False})
    # en este sendrequest preguntar a juampi sobre el data
    r = sendRequest(method="get", url="/sensors-info")
    filter.sensorId.choices = [
        (int(sensor["id"]), sensor["name"]) for sensor in json.loads(r.text)["Sensors"]
    ]
    filter.sensorId.choices.insert(0, [0, "All"])
    data = {}
    # comienzo el filtrado
    # Valido el formulario de Filtros
    if filter.validate():
        # filtro de la fecha
        if filter.datetimede.data and filter.datetimeTo.data:
            if filter.datetimede.data == filter.datetimeTo.data:
                data["datetime"] = filter.datetimeTo.data.strftime("%Y-%m-%d %H:%M")
        if filter.datetimede.data != None:
            data["datetimede"] = filter.datetimede.data.strftime("%Y-%m-%d %H:%M")
        if filter.datetimeTo.data != None:
            data["datetimeTo"] = filter.datetimeTo.data.strftime("%Y-%m-%d %H:%M")

        # filtro de la profundidad o Depth
        if filter.depthMin.data != None:
            data["depthMin"] = filter.depthMin.data
        if filter.depthMax.data != None:
            data["depthMax"] = filter.depthMax.data

        # filtro de la magnitud o Magnitude
        if filter.magnitudeMin.data != None:
            data["magnitudeMin"] = filter.magnitudeMin.data
        if filter.magnitudeMax.data != None:
            data["magnitudeMax"] = filter.magnitudeMax.data

        # filtro de sensor por identificacion
        if filter.sensorId.data != None and filter.sensorId.data != 0:
            data["sensorId"] = filter.sensorId.data

    # Comienzo con el ORDENAMIENTO
    if "sort_by" in request.args:
        data["sort_by"] = request.args.get("sort_by", "")

    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]

    # Obtenego los datos de la api para la tabla
    r = sendRequest(
        method="get", url="/unverified-seisms", data=json.dumps(data), auth=True
    )

    # si me da correcto abro un if para poder seguir
    if r.status_code == 200:
        unverified_seisms = json.loads(r.text)["Unverified-Seisms"]
        pagination = {}
        # cargo en el diccionario de la paginacion el total de las paginas
        # pagina por pagina
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]
        title = "Unverified Seisms List"

        return render_template(
            "unverified_seisms.html",
            title=title,
            unverified_seisms=unverified_seisms,
            filter=filter,
            pagination=pagination,
        )
    else:
        flash("Error en el filtrado", "danger")
        return redirect(url_for("unverified_seism.index"))


# tengo que agregarle el def view (id) para poder que me vaya devolviendo el numero de identificacion
@unverified_seism.route("/view/<int:id>")
@login_required
@register_breadcrumb(unverified_seism, ".view", "UnverifiedSeisms")
def view(id):
    r = sendRequest(method="get", url="/unverified-seism/" + str(id), auth=True)
    if r.status_code == 404:
        flash("Seism not found/Sismo no encontrado", "danger")
        return redirect(url_for("unverified_seism.index"))
    unverified_seism = json.loads(r.text)
    title = "Unverified Seism Details"
    return render_template(
        "unverified_seismView.html", title=title, unverified_seism=unverified_seism
    )


# defino la variable para eliminar esta no necesita ser admin yaque lo ven los simologos
@unverified_seism.route("/delete/<int:id>")
@login_required
def delete(id):
    r = sendRequest(method="delete", url="/unverified-seism")
    flash("Unverified Seims ", "danger")
    return redirect(url_for("unverified_seism.index"))


# testeando la funcion con prints porque tengo problemas con la base de datos
@login_required
@register_breadcrumb(unverified_seism, ".edit", "Edita Unverified Seismos")
@unverified_seism.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):

    form = UnverifiedSeismEdit()
    if not form.is_submitted():
        r = sendRequest(method="get", url="/unverified-seism/" + str(id), auth=True)
        if r.status_code == 404:
            flash("unverified seism not foun", "danger")
            return redirect(url_for("unverified_seism.index"))

        unverified_seism = json.loads(r.text)
        form.depth.data = unverified_seism["depth"]
        form.magnitude.data = unverified_seism["magnitude"]
        form.verified.data = unverified_seism["verified"]

    # en la siguiente linea se produce la validacion del sismo pasandole los datos del diccionario anterior
    # por eso utilizo [""] diccionario
    if form.validate_on_submit():
        unverified_seism = {
            "depth": form.depth.data,
            "magnitude": form.magnitude.data,
            "verified": form.verified.data,
        }
        data = json.dumps(unverified_seism)
        r = sendRequest(
            method="PUT", url="/unverified-seism/" + str(id), data=data, auth=True
        )
        flash("Unverified Seism was edited", "success")
        return redirect(url_for("unverified_seism.index"))
    return render_template(
        "unverified_seismEdit.html",
        unverified_seism=unverified_seism,
        form=form,
    )

seismology/web/main/routes/users.py
import json

# from web.main.routes.auth import admin_required
from ..forms.user_forms import UserCreateForm, UserEdit
from flask import (
    Blueprint,
    render_template,
    current_app,
    redirect,
    url_for,
    flash,
    request,
)
from flask import blueprints
from werkzeug.utils import header_property
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from ..utilities.functions import sendRequest
import requests
from flask_login import login_required

# from .auth import admin_required

users = Blueprint("users", __name__, url_prefix="/users")


# @admin_required
# @login_required
@users.route("/")
@login_required
@register_breadcrumb(users, ".", "Users")
def index():
    data = {}
    # Numero de pagina
    if "page" in request.args:
        data["page"] = request.args.get("page", "")
    else:
        if "page" in data:
            del data["page"]
    r = sendRequest(method="get", url="/users", data=json.dumps(data), auth=True)

    if r.status_code == 200:
        users = json.loads(r.text)["Users"]

        pagination = {}
        pagination["total"] = json.loads(r.text)["total"]
        pagination["pages"] = json.loads(r.text)["pages"]
        pagination["current_page"] = json.loads(r.text)["page"]

        title = "Users List"
        # el primer user es la variable que esta en el template del html de user en el for el segundo users es la variable de aca arriba del index
        return render_template(
            "user.html",
            title=title,
            users=users,
            pagination=pagination,
        )
    else:
        return redirect(url_for("users.index"))


@users.route("/add", methods=["GET", "POST"])
def create():
    form = UserCreateForm()
    title = "Add user"
    if form.validate_on_submit():
        user = {
            "email": form.email.data,
            "password": form.password.data,
            "admin": form.admin.data,
        }
        # dumps googlearlo
        data = json.dumps(user)
        r = sendRequest(method="POST", url="/users", data=data)

        return redirect(url_for("users.index"))  # me direcicona a la tabla
    # me muestra el formulario
    return render_template("add_user.html", title=title, form=form)


@users.route("/edit/<int:id>", methods=["GET", "POST"])
@register_breadcrumb(users, ".edit", "Edit User")
def edit(id):
    form = UserEdit()
    if not form.is_submitted():
        r = sendRequest(method="get", url="/user/" + str(id), auth=True)
        if r.status_code == 404:
            flash("User not Found/Usuario no encontrado", "danger")
            return redirect(url_for("users.index"))
        user = json.loads(r.text)
        form.email.data = user["email"]
        form.admin.data = user["admin"]

    if form.validate_on_submit():
        user = {"email": form.email.data, "admin": form.admin.data}

        data = json.dumps(user)
        r = sendRequest(method="PUT", url="/user/" + str(id), data=data, auth=True)
        flash("User edited/Usuario Editado", "success")
        return redirect(url_for("users.index"))
    return render_template("userEdit.html", form=form, id=id)


@users.route("/delete/<int:id>")
def delete(id):
    r = sendRequest(method="delete", url="/user/" + str(id), auth=True)
    flash("User was delete", "danger")
    return redirect(url_for("users.index"))

seismology/web/main/templates/add_user.html
<!-- Hereda del template main -->

{% extends "main.html" %}

<!-- Importar el archivo de macros -->
{% import "macros.html" as macro %}

<!-- Importar macros de formulario -->
{% from "form_macros.html" import show_field, show_submit, show_checkbox %}

{% block content %}
<!--Content-->
<div class="container  text-white">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1>{{title}}</h1>
            <form method="POST" action="{{url_for('users.create')}}">
                <!-- hidden estara escondide no lo puede tocar nadie -->
                <input type="hidden" name="csrf_token" value="{{csrf_token() }}" />
                <div class=" form-row">
                    {{ show_field(form.email, class="form-control") }}
                </div>

                <div class="form-group">
                    {{ show_field(form.password, class="form-control") }} <br>
                    {{ show_field(form.confirm, class="form-control") }}

                </div>
                <div class="form-row">
                    {{show_checkbox(form.admin)}}
                </div>
                {{show_submit(form.submit)}}
            </form>
        </div>


    </div>
</div>
<!-- Fin de contenido -->
{% endblock %}

seismology/web/main/templates/macros.html
{% macro show_verified_seism(verified_seism) %}
<tr>
    <th scope="row">{{verified_seism.id}}</th>
    <td>{{verified_seism.datetime}}</td>
    <td>{{verified_seism.depth}}</td>
    <td>{{verified_seism.magnitude}}</td>
    <td>{{verified_seism.sensor.name}}</td>
    <td>
        <div class="btn-group" role="group">

            <a class="btn btn-sm btn-dark" type="button"
                href="{{ url_for('verified_seism.view',id=verified_seism.id) }}">
                <i class="fas fa-eye"></i></a>


        </div>
    </td>
</tr>
{% endmacro %}

{% macro show_unverified_seism(unverified_seism) %}
<tr>
    <th scope="row">{{unverified_seism.id}}</th>
    <td>{{unverified_seism.datetime}}</td>
    <td>{{unverified_seism.depth}}</td>
    <td>{{unverified_seism.magnitude}}</td>
    <td>{{unverified_seism.sensor.name}}</td>
    <td>
        <div class="btn-group" role="group">

            <a class="btn btn-sm btn-dark" type="button"
                href="{{ url_for('unverified_seism.view',id=unverified_seism.id) }}">
                <i class="fas fa-eye"></i></a>

            <a class="btn btn-sm btn-dark" type="button"
                href="{{ url_for('unverified_seism.edit',id=unverified_seism.id) }}">
                <i class="fas fa-edit"></i></a>

            <a class="btn btn-sm btn-dark" type="button"
                href="{{ url_for('unverified_seism.delete',id=unverified_seism.id) }}">
                <i class="fas fa-trash"></i></a>

        </div>
    </td>
</tr>
{% endmacro %}

{% macro show_sensor(sensor) %}
<tr>
    <th scope="row">{{sensor.id}}</th>
    <td>{{sensor.name}}</td>
    <td>{{sensor.status}}</td>
    <td>{{sensor.active}}</td>
    <td>
        {% if sensor.user %}
        {{sensor.user.email}}
        {% endif %}
    </td>
    <td>
        <div class="btn-group" role="group">
            <a class="btn btn-sm btn-dark" type="button" href="{{ url_for('sensors.view',id=sensor.id) }}">
                <i class="fas fa-eye"></i></a>

            <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensors.delete',id=sensor.id)}}">
                <i class="fas fa-trash"></i></a>

            <a class="btn btn-sm btn-dark" type="button" href="{{url_for('sensors.edit', id=sensor.id)}}">
                <i class="fas fa-edit"></i></a>
        </div>
    </td>
</tr>
{% endmacro %}

{% macro show_user(user) %}
<tr>
    <th scope="row">{{user.id}}</th>
    <td>{{user.email}}</td>
    <td>{{user.admin}}</td>
    <td>
        <div class="btn-group" role="group">

            <a class="btn btn-sm btn-dark" type="button" href="{{url_for('users.delete',id=user.id)}}">
                <i class="fas fa-trash"></i></a>

            <a class="btn btn-sm btn-dark" type="button" href="{{url_for('users.edit', id=user.id)}}">
                <i class="fas fa-edit"></i></a>
        </div>
    </td>
</tr>
{% endmacro %}

seismology/web/main/templates/main.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Proyecto Seisms</title>
  {% block head %}
  <!-- style css only-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <!-- style css local-->
  <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

  {% endblock %}
</head>

<body>
  {% block script %}
  <!-- js -->
  <script src=" https://code.jquery.com/jquery-3.5.1.slim.min.js">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/ec398cbdc7.js"></script>
  <script>
    $(function () { $('[data-toggle="tooltip"]').tooltip() })
  </script>
  {% endblock %}

  {% block menu %}
  <!-- Header -->
  <header>
    <nav class="navbar navbar-expand-lg navbar-light ">
      <a class="navbar-brand text-light" href="{{url_for('main.index')}}"><i class="fas fa-server text-light"></i>
        Seismology</a>

      <!--items -->
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="navbar-nav mr-auto">
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
            {% if current_user.admin %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{{url_for('sensors.index')}}">Sensors</a>
            </li>


            <li class="nav-item">
              <a class="nav-link text-light" href="{{url_for('users.index')}}">Users</a>
            </li>
            {% endif %}
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdownMenuLink" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Seisms
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                <a class="dropdown-item " href="{{url_for('verified_seism.index')}}">Verified Seisms</a>
                {% if current_user.is_authenticated %}
                <a class="dropdown-item" href="{{url_for('unverified_seism.index')}}">Unverified Seisms</a>
                {% endif %}
              </div>
            </li>
          </ul>
        </div>


        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
          <li><a class="btn btn-secondary" href="{{url_for('users.index')}}"><i class="fas fa-user"></i></a></li>
          <li><a class="btn btn-secondary" href="{{url_for('verified_seism.index')}}"><i
                class="fas fa-house-user"></i></a></li>
          <li><a class="btn btn-secondary" href="{{url_for('login.logout')}}"><i class="fas fa-sign-out-alt"></i>
              Logout</a>
          </li>
          {% else %}
          <li><a class="btn btn-secondary" href="{{url_for('login.login')}}"><i class="fas fa-sign-in-alt"></i>
              Login</a>
          </li>
          {% endif %}

        </ul>

    </nav>
  </header>
  {% endblock %}

  {% block breadcrumbs %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-dark">
      {% for breadcrumb in breadcrumbs %}
      <li class="breadcrumb-item">
        {% if not loop.last %}
        <a class="text-light" href="{{ breadcrumb.url }}">{{ breadcrumb.text }}</a>
        {% else %}
        {{ breadcrumb.text }}
        {{ "/" if not loop.last }}
        {% endif %}
      </li>
      {% endfor %}
    </ol>
  </nav>
  {% endblock %}
  {% block flash %}
  <div class="container-fluid">
    <div style="position: relative">
      <div style="position: absolute; top: 0; right: 0;">
        <div class="col-auto mx-auto">
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>
  {% endblock %}

  </br></br>

  {%block content %}
  <!--Content-->
  {% endblock %}
  <br> <br>
  {% block footer %}
  <!-- FOOTER -->
  <footer class="footer fixed-bottom mt-auto py-3">
    <div class="container">
      <div class="text-left text-light"> © 2020 Copyright:
        <a class="text-light" href="https://las.op.gg/summoner/userName=God%20illuminated">God illuminated</a>
      </div>

    </div>

  </footer>
  {% endblock %}

</body>

</html>

seismology/web/main/templates/sensorview.html
<!-- Hereda del template main -->

{% extends "main.html" %}

<!-- Importar el archivo de macros -->
{% import "macros.html" as macro %}

{% block content %}
<!--Content-->

<div class="container text-white">
    <div class="row justify-content-center">
        <div class="col-md-2 d-none d-md-block"></div>
        <div class="col-md-auto">
            <h1>DETAILED SENSOR</h1>
            <div class="table-responsive text-left">
                <table class="table table-dark table-striped table-hover table-bordered">
                    <caption>
                        <a name="modify" class="btn btn-success" href="{{url_for('sensors.edit',id=sensor.id)}}"
                            role="button">Modify</a>
                        <a name="delete" class="btn btn-danger" href="{{url_for('sensors.delete',id=sensor.id)}}"
                            role="button">Delete</a>
                    </caption>
                    <tbody>
                        <tr>
                            <th scope="col">#</th>
                            <td>{{sensor.id}}</td>
                        </tr>
                        <tr>
                            <th scope="col">Name</th>
                            <td>{{sensor.name}}</td>
                        </tr>
                        <tr>
                            <th scope="col">PORT</th>
                            <td>{{sensor.port}}</td>
                        </tr>
                        <tr>
                            <th scope="col">IP</th>
                            <td>{{sensor.ip}}</td>

                        </tr>
                        <tr>
                            <<th scope="col">Status</th>
                                <td>{{sensor.status}}</td>
                        </tr>
                        <tr>
                            <th scope="col">Active</th>
                            <td>{{sensor.active}}</td>
                        </tr>
                        <tr>
                            <th scope="col">User Assigned</th>
                            <td>{% if sensor.user %}
                                {{sensor.user.email}}
                                {% endif %}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-md-2 d-none d-md-block"></div>
    </div>
</div>

{% endblock %}